apiVersion: v1
kind: Service
metadata:
  name: template-service
  namespace: demo
  labels:
    app: template-app
spec:
  selector:
    app: template-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
