apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-app
  namespace: dev
  labels:
    app: template-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-app
  template:
    metadata:
      labels:
        app: template-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: nginx
        image: 548840552729.dkr.ecr.ap-southeast-1.amazonaws.com/template-api:latest
        imagePullPolicy: Always
        env:
          - name: POSTGRES_HOST
            value: "dev-postgres-1.ckmnwuidk279.ap-southeast-1.rds.amazonaws.com"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_USER
            value: "appuser"
          - name: POSTGRES_PASSWORD
            value: "q0GRy2GrstgleNQmhJMWrQR"
          - name: POSTGRES_DB
            value: "appuser"
          - name: TEST_ENV
            value: "false"
          - name: SERVER_HOST
            value: "0.0.0.0"
          - name: SERVER_PORT
            value: "8080"
          - name: SERVER_LOG_LEVEL
            value: "development"
          - name: NATS_HOST
            value: "nats.nats.svc.cluster.local"
          - name: NATS_PORT
            value: "4222"
          - name: SWAGGER_URL
            value: "https://api2.dev.engagerocket.co/api/v1/template/docs/swagger.json"
          - name: OAUTH_AUDIENCES
            # Default App client_id (available in aud claim in JWT). See Auth0 applications
            value: "JAOtymvTUj1uHWFguMN1Q4OKk6AfLzYw"
          - name: OAUTH_DOMAIN
            value: dev-5pog45aw8mxft1cm.eu.auth0.com
          - name: SWAGGER_HOST
            value: "api2.dev.engagerocket.co"
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            memory: "128Mi" 
            cpu: "0.1"      
          requests:
            memory: "128Mi" 
            cpu: "0.1"     
      nodeSelector:
        kubernetes.io/os: linux