version: '3.8'

networks:
  template-api-svc-network:
    name: template-api-svc-network

services:
  template-api-svc-postgres:
    image: postgres:15-alpine
    hostname: postgres
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: template-api
      POSTGRES_PASSWORD: template-api
      POSTGRES_DB: template-api
    networks:
      - template-api-svc-network

