//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AttributeType = newAttributeTypeTable("public", "attribute_type", "")

type attributeTypeTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnInteger
	Name        postgres.ColumnString
	Description postgres.ColumnString
	Code        postgres.ColumnString
	CreatedAt   postgres.ColumnTimestamp
	UpdatedAt   postgres.ColumnTimestamp
	CreatedBy   postgres.ColumnInteger
	UpdatedBy   postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type AttributeTypeTable struct {
	attributeTypeTable

	EXCLUDED attributeTypeTable
}

// AS creates new AttributeTypeTable with assigned alias
func (a AttributeTypeTable) AS(alias string) *AttributeTypeTable {
	return newAttributeTypeTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AttributeTypeTable with assigned schema name
func (a AttributeTypeTable) FromSchema(schemaName string) *AttributeTypeTable {
	return newAttributeTypeTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AttributeTypeTable with assigned table prefix
func (a AttributeTypeTable) WithPrefix(prefix string) *AttributeTypeTable {
	return newAttributeTypeTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AttributeTypeTable with assigned table suffix
func (a AttributeTypeTable) WithSuffix(suffix string) *AttributeTypeTable {
	return newAttributeTypeTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAttributeTypeTable(schemaName, tableName, alias string) *AttributeTypeTable {
	return &AttributeTypeTable{
		attributeTypeTable: newAttributeTypeTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newAttributeTypeTableImpl("", "excluded", ""),
	}
}

func newAttributeTypeTableImpl(schemaName, tableName, alias string) attributeTypeTable {
	var (
		IDColumn          = postgres.IntegerColumn("id")
		NameColumn        = postgres.StringColumn("name")
		DescriptionColumn = postgres.StringColumn("description")
		CodeColumn        = postgres.StringColumn("code")
		CreatedAtColumn   = postgres.TimestampColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampColumn("updated_at")
		CreatedByColumn   = postgres.IntegerColumn("created_by")
		UpdatedByColumn   = postgres.IntegerColumn("updated_by")
		allColumns        = postgres.ColumnList{IDColumn, NameColumn, DescriptionColumn, CodeColumn, CreatedAtColumn, UpdatedAtColumn, CreatedByColumn, UpdatedByColumn}
		mutableColumns    = postgres.ColumnList{NameColumn, DescriptionColumn, CodeColumn, CreatedAtColumn, UpdatedAtColumn, CreatedByColumn, UpdatedByColumn}
	)

	return attributeTypeTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Name:        NameColumn,
		Description: DescriptionColumn,
		Code:        CodeColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,
		CreatedBy:   CreatedByColumn,
		UpdatedBy:   UpdatedByColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
