//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Countries = newCountriesTable("public", "countries", "")

type countriesTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnInteger
	Name        postgres.ColumnString
	Code        postgres.ColumnString
	Description postgres.ColumnString
	CreatedAt   postgres.ColumnTimestamp
	UpdatedAt   postgres.ColumnTimestamp
	CreatedBy   postgres.ColumnInteger
	UpdatedBy   postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type CountriesTable struct {
	countriesTable

	EXCLUDED countriesTable
}

// AS creates new CountriesTable with assigned alias
func (a CountriesTable) AS(alias string) *CountriesTable {
	return newCountriesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CountriesTable with assigned schema name
func (a CountriesTable) FromSchema(schemaName string) *CountriesTable {
	return newCountriesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CountriesTable with assigned table prefix
func (a CountriesTable) WithPrefix(prefix string) *CountriesTable {
	return newCountriesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CountriesTable with assigned table suffix
func (a CountriesTable) WithSuffix(suffix string) *CountriesTable {
	return newCountriesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCountriesTable(schemaName, tableName, alias string) *CountriesTable {
	return &CountriesTable{
		countriesTable: newCountriesTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newCountriesTableImpl("", "excluded", ""),
	}
}

func newCountriesTableImpl(schemaName, tableName, alias string) countriesTable {
	var (
		IDColumn          = postgres.IntegerColumn("id")
		NameColumn        = postgres.StringColumn("name")
		CodeColumn        = postgres.StringColumn("code")
		DescriptionColumn = postgres.StringColumn("description")
		CreatedAtColumn   = postgres.TimestampColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampColumn("updated_at")
		CreatedByColumn   = postgres.IntegerColumn("created_by")
		UpdatedByColumn   = postgres.IntegerColumn("updated_by")
		allColumns        = postgres.ColumnList{IDColumn, NameColumn, CodeColumn, DescriptionColumn, CreatedAtColumn, UpdatedAtColumn, CreatedByColumn, UpdatedByColumn}
		mutableColumns    = postgres.ColumnList{NameColumn, CodeColumn, DescriptionColumn, CreatedAtColumn, UpdatedAtColumn, CreatedByColumn, UpdatedByColumn}
	)

	return countriesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Name:        NameColumn,
		Code:        CodeColumn,
		Description: DescriptionColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,
		CreatedBy:   CreatedByColumn,
		UpdatedBy:   UpdatedByColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
