//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var EngageRocketAdmins = newEngageRocketAdminsTable("public", "engage_rocket_admins", "")

type engageRocketAdminsTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	UserID    postgres.ColumnInteger
	UpdatedAt postgres.ColumnTimestamp
	CreatedAt postgres.ColumnTimestamp
	UpdatedBy postgres.ColumnInteger
	CreatedBy postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type EngageRocketAdminsTable struct {
	engageRocketAdminsTable

	EXCLUDED engageRocketAdminsTable
}

// AS creates new EngageRocketAdminsTable with assigned alias
func (a EngageRocketAdminsTable) AS(alias string) *EngageRocketAdminsTable {
	return newEngageRocketAdminsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EngageRocketAdminsTable with assigned schema name
func (a EngageRocketAdminsTable) FromSchema(schemaName string) *EngageRocketAdminsTable {
	return newEngageRocketAdminsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EngageRocketAdminsTable with assigned table prefix
func (a EngageRocketAdminsTable) WithPrefix(prefix string) *EngageRocketAdminsTable {
	return newEngageRocketAdminsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EngageRocketAdminsTable with assigned table suffix
func (a EngageRocketAdminsTable) WithSuffix(suffix string) *EngageRocketAdminsTable {
	return newEngageRocketAdminsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEngageRocketAdminsTable(schemaName, tableName, alias string) *EngageRocketAdminsTable {
	return &EngageRocketAdminsTable{
		engageRocketAdminsTable: newEngageRocketAdminsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                newEngageRocketAdminsTableImpl("", "excluded", ""),
	}
}

func newEngageRocketAdminsTableImpl(schemaName, tableName, alias string) engageRocketAdminsTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		UserIDColumn    = postgres.IntegerColumn("user_id")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedByColumn = postgres.IntegerColumn("updated_by")
		CreatedByColumn = postgres.IntegerColumn("created_by")
		allColumns      = postgres.ColumnList{IDColumn, UserIDColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn}
		mutableColumns  = postgres.ColumnList{UserIDColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn}
	)

	return engageRocketAdminsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		UserID:    UserIDColumn,
		UpdatedAt: UpdatedAtColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedBy: UpdatedByColumn,
		CreatedBy: CreatedByColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
