//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var EntitySettings = newEntitySettingsTable("public", "entity_settings", "")

type entitySettingsTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnInteger
	Name            postgres.ColumnString
	AdminCount      postgres.ColumnInteger
	UserCount       postgres.ColumnInteger
	EmployeeCount   postgres.ColumnInteger
	ActiveSeatCount postgres.ColumnInteger
	BeginDate       postgres.ColumnTimestamp
	EndDate         postgres.ColumnTimestamp
	EntityID        postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type EntitySettingsTable struct {
	entitySettingsTable

	EXCLUDED entitySettingsTable
}

// AS creates new EntitySettingsTable with assigned alias
func (a EntitySettingsTable) AS(alias string) *EntitySettingsTable {
	return newEntitySettingsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EntitySettingsTable with assigned schema name
func (a EntitySettingsTable) FromSchema(schemaName string) *EntitySettingsTable {
	return newEntitySettingsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EntitySettingsTable with assigned table prefix
func (a EntitySettingsTable) WithPrefix(prefix string) *EntitySettingsTable {
	return newEntitySettingsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EntitySettingsTable with assigned table suffix
func (a EntitySettingsTable) WithSuffix(suffix string) *EntitySettingsTable {
	return newEntitySettingsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEntitySettingsTable(schemaName, tableName, alias string) *EntitySettingsTable {
	return &EntitySettingsTable{
		entitySettingsTable: newEntitySettingsTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newEntitySettingsTableImpl("", "excluded", ""),
	}
}

func newEntitySettingsTableImpl(schemaName, tableName, alias string) entitySettingsTable {
	var (
		IDColumn              = postgres.IntegerColumn("id")
		NameColumn            = postgres.StringColumn("name")
		AdminCountColumn      = postgres.IntegerColumn("admin_count")
		UserCountColumn       = postgres.IntegerColumn("user_count")
		EmployeeCountColumn   = postgres.IntegerColumn("employee_count")
		ActiveSeatCountColumn = postgres.IntegerColumn("active_seat_count")
		BeginDateColumn       = postgres.TimestampColumn("begin_date")
		EndDateColumn         = postgres.TimestampColumn("end_date")
		EntityIDColumn        = postgres.IntegerColumn("entity_id")
		allColumns            = postgres.ColumnList{IDColumn, NameColumn, AdminCountColumn, UserCountColumn, EmployeeCountColumn, ActiveSeatCountColumn, BeginDateColumn, EndDateColumn, EntityIDColumn}
		mutableColumns        = postgres.ColumnList{NameColumn, AdminCountColumn, UserCountColumn, EmployeeCountColumn, ActiveSeatCountColumn, BeginDateColumn, EndDateColumn, EntityIDColumn}
	)

	return entitySettingsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		Name:            NameColumn,
		AdminCount:      AdminCountColumn,
		UserCount:       UserCountColumn,
		EmployeeCount:   EmployeeCountColumn,
		ActiveSeatCount: ActiveSeatCountColumn,
		BeginDate:       BeginDateColumn,
		EndDate:         EndDateColumn,
		EntityID:        EntityIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
