//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var FeatureType = newFeatureTypeTable("public", "feature_type", "")

type featureTypeTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnInteger
	Description postgres.ColumnString
	Name        postgres.ColumnString
	Code        postgres.ColumnString
	CreatedAt   postgres.ColumnTimestamp
	UpdatedAt   postgres.ColumnTimestamp
	CreatedBy   postgres.ColumnInteger
	UpdatedBy   postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type FeatureTypeTable struct {
	featureTypeTable

	EXCLUDED featureTypeTable
}

// AS creates new FeatureTypeTable with assigned alias
func (a FeatureTypeTable) AS(alias string) *FeatureTypeTable {
	return newFeatureTypeTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FeatureTypeTable with assigned schema name
func (a FeatureTypeTable) FromSchema(schemaName string) *FeatureTypeTable {
	return newFeatureTypeTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FeatureTypeTable with assigned table prefix
func (a FeatureTypeTable) WithPrefix(prefix string) *FeatureTypeTable {
	return newFeatureTypeTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FeatureTypeTable with assigned table suffix
func (a FeatureTypeTable) WithSuffix(suffix string) *FeatureTypeTable {
	return newFeatureTypeTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFeatureTypeTable(schemaName, tableName, alias string) *FeatureTypeTable {
	return &FeatureTypeTable{
		featureTypeTable: newFeatureTypeTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newFeatureTypeTableImpl("", "excluded", ""),
	}
}

func newFeatureTypeTableImpl(schemaName, tableName, alias string) featureTypeTable {
	var (
		IDColumn          = postgres.IntegerColumn("id")
		DescriptionColumn = postgres.StringColumn("description")
		NameColumn        = postgres.StringColumn("name")
		CodeColumn        = postgres.StringColumn("code")
		CreatedAtColumn   = postgres.TimestampColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampColumn("updated_at")
		CreatedByColumn   = postgres.IntegerColumn("created_by")
		UpdatedByColumn   = postgres.IntegerColumn("updated_by")
		allColumns        = postgres.ColumnList{IDColumn, DescriptionColumn, NameColumn, CodeColumn, CreatedAtColumn, UpdatedAtColumn, CreatedByColumn, UpdatedByColumn}
		mutableColumns    = postgres.ColumnList{DescriptionColumn, NameColumn, CodeColumn, CreatedAtColumn, UpdatedAtColumn, CreatedByColumn, UpdatedByColumn}
	)

	return featureTypeTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Description: DescriptionColumn,
		Name:        NameColumn,
		Code:        CodeColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,
		CreatedBy:   CreatedByColumn,
		UpdatedBy:   UpdatedByColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
