//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var OrganizationalStructure = newOrganizationalStructureTable("public", "organizational_structure", "")

type organizationalStructureTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnInteger
	Name        postgres.ColumnString
	Code        postgres.ColumnString
	Description postgres.ColumnString
	CreatedAt   postgres.ColumnTimestamp
	UpdatedAt   postgres.ColumnTimestamp
	CreatedBy   postgres.ColumnInteger
	UpdatedBy   postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type OrganizationalStructureTable struct {
	organizationalStructureTable

	EXCLUDED organizationalStructureTable
}

// AS creates new OrganizationalStructureTable with assigned alias
func (a OrganizationalStructureTable) AS(alias string) *OrganizationalStructureTable {
	return newOrganizationalStructureTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new OrganizationalStructureTable with assigned schema name
func (a OrganizationalStructureTable) FromSchema(schemaName string) *OrganizationalStructureTable {
	return newOrganizationalStructureTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new OrganizationalStructureTable with assigned table prefix
func (a OrganizationalStructureTable) WithPrefix(prefix string) *OrganizationalStructureTable {
	return newOrganizationalStructureTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new OrganizationalStructureTable with assigned table suffix
func (a OrganizationalStructureTable) WithSuffix(suffix string) *OrganizationalStructureTable {
	return newOrganizationalStructureTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newOrganizationalStructureTable(schemaName, tableName, alias string) *OrganizationalStructureTable {
	return &OrganizationalStructureTable{
		organizationalStructureTable: newOrganizationalStructureTableImpl(schemaName, tableName, alias),
		EXCLUDED:                     newOrganizationalStructureTableImpl("", "excluded", ""),
	}
}

func newOrganizationalStructureTableImpl(schemaName, tableName, alias string) organizationalStructureTable {
	var (
		IDColumn          = postgres.IntegerColumn("id")
		NameColumn        = postgres.StringColumn("name")
		CodeColumn        = postgres.StringColumn("code")
		DescriptionColumn = postgres.StringColumn("description")
		CreatedAtColumn   = postgres.TimestampColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampColumn("updated_at")
		CreatedByColumn   = postgres.IntegerColumn("created_by")
		UpdatedByColumn   = postgres.IntegerColumn("updated_by")
		allColumns        = postgres.ColumnList{IDColumn, NameColumn, CodeColumn, DescriptionColumn, CreatedAtColumn, UpdatedAtColumn, CreatedByColumn, UpdatedByColumn}
		mutableColumns    = postgres.ColumnList{NameColumn, CodeColumn, DescriptionColumn, CreatedAtColumn, UpdatedAtColumn, CreatedByColumn, UpdatedByColumn}
	)

	return organizationalStructureTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Name:        NameColumn,
		Code:        CodeColumn,
		Description: DescriptionColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,
		CreatedBy:   CreatedByColumn,
		UpdatedBy:   UpdatedByColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
