//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PermissionCategory = newPermissionCategoryTable("public", "permission_category", "")

type permissionCategoryTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnInteger
	Name        postgres.ColumnString
	Code        postgres.ColumnString
	Description postgres.ColumnString
	CreatedAt   postgres.ColumnTimestamp
	UpdatedAt   postgres.ColumnTimestamp
	CreatedBy   postgres.ColumnInteger
	UpdatedBy   postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PermissionCategoryTable struct {
	permissionCategoryTable

	EXCLUDED permissionCategoryTable
}

// AS creates new PermissionCategoryTable with assigned alias
func (a PermissionCategoryTable) AS(alias string) *PermissionCategoryTable {
	return newPermissionCategoryTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PermissionCategoryTable with assigned schema name
func (a PermissionCategoryTable) FromSchema(schemaName string) *PermissionCategoryTable {
	return newPermissionCategoryTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PermissionCategoryTable with assigned table prefix
func (a PermissionCategoryTable) WithPrefix(prefix string) *PermissionCategoryTable {
	return newPermissionCategoryTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PermissionCategoryTable with assigned table suffix
func (a PermissionCategoryTable) WithSuffix(suffix string) *PermissionCategoryTable {
	return newPermissionCategoryTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPermissionCategoryTable(schemaName, tableName, alias string) *PermissionCategoryTable {
	return &PermissionCategoryTable{
		permissionCategoryTable: newPermissionCategoryTableImpl(schemaName, tableName, alias),
		EXCLUDED:                newPermissionCategoryTableImpl("", "excluded", ""),
	}
}

func newPermissionCategoryTableImpl(schemaName, tableName, alias string) permissionCategoryTable {
	var (
		IDColumn          = postgres.IntegerColumn("id")
		NameColumn        = postgres.StringColumn("name")
		CodeColumn        = postgres.StringColumn("code")
		DescriptionColumn = postgres.StringColumn("description")
		CreatedAtColumn   = postgres.TimestampColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampColumn("updated_at")
		CreatedByColumn   = postgres.IntegerColumn("created_by")
		UpdatedByColumn   = postgres.IntegerColumn("updated_by")
		allColumns        = postgres.ColumnList{IDColumn, NameColumn, CodeColumn, DescriptionColumn, CreatedAtColumn, UpdatedAtColumn, CreatedByColumn, UpdatedByColumn}
		mutableColumns    = postgres.ColumnList{NameColumn, CodeColumn, DescriptionColumn, CreatedAtColumn, UpdatedAtColumn, CreatedByColumn, UpdatedByColumn}
	)

	return permissionCategoryTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Name:        NameColumn,
		Code:        CodeColumn,
		Description: DescriptionColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,
		CreatedBy:   CreatedByColumn,
		UpdatedBy:   UpdatedByColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
