//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var QuestionDimension = newQuestionDimensionTable("public", "question_dimension", "")

type questionDimensionTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnInteger
	Name            postgres.ColumnString
	Code            postgres.ColumnString
	Description     postgres.ColumnString
	UpdatedAt       postgres.ColumnTimestamp
	CreatedAt       postgres.ColumnTimestamp
	UpdatedBy       postgres.ColumnInteger
	CreatedBy       postgres.ColumnInteger
	QueueNumber     postgres.ColumnInteger
	IconColor       postgres.ColumnString
	IdCustomSvgIcon postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type QuestionDimensionTable struct {
	questionDimensionTable

	EXCLUDED questionDimensionTable
}

// AS creates new QuestionDimensionTable with assigned alias
func (a QuestionDimensionTable) AS(alias string) *QuestionDimensionTable {
	return newQuestionDimensionTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new QuestionDimensionTable with assigned schema name
func (a QuestionDimensionTable) FromSchema(schemaName string) *QuestionDimensionTable {
	return newQuestionDimensionTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new QuestionDimensionTable with assigned table prefix
func (a QuestionDimensionTable) WithPrefix(prefix string) *QuestionDimensionTable {
	return newQuestionDimensionTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new QuestionDimensionTable with assigned table suffix
func (a QuestionDimensionTable) WithSuffix(suffix string) *QuestionDimensionTable {
	return newQuestionDimensionTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newQuestionDimensionTable(schemaName, tableName, alias string) *QuestionDimensionTable {
	return &QuestionDimensionTable{
		questionDimensionTable: newQuestionDimensionTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newQuestionDimensionTableImpl("", "excluded", ""),
	}
}

func newQuestionDimensionTableImpl(schemaName, tableName, alias string) questionDimensionTable {
	var (
		IDColumn              = postgres.IntegerColumn("id")
		NameColumn            = postgres.StringColumn("name")
		CodeColumn            = postgres.StringColumn("code")
		DescriptionColumn     = postgres.StringColumn("description")
		UpdatedAtColumn       = postgres.TimestampColumn("updated_at")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		UpdatedByColumn       = postgres.IntegerColumn("updated_by")
		CreatedByColumn       = postgres.IntegerColumn("created_by")
		QueueNumberColumn     = postgres.IntegerColumn("queueNumber")
		IconColorColumn       = postgres.StringColumn("iconColor")
		IdCustomSvgIconColumn = postgres.IntegerColumn("idCustomSvgIcon")
		allColumns            = postgres.ColumnList{IDColumn, NameColumn, CodeColumn, DescriptionColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, QueueNumberColumn, IconColorColumn, IdCustomSvgIconColumn}
		mutableColumns        = postgres.ColumnList{NameColumn, CodeColumn, DescriptionColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, QueueNumberColumn, IconColorColumn, IdCustomSvgIconColumn}
	)

	return questionDimensionTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		Name:            NameColumn,
		Code:            CodeColumn,
		Description:     DescriptionColumn,
		UpdatedAt:       UpdatedAtColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedBy:       UpdatedByColumn,
		CreatedBy:       CreatedByColumn,
		QueueNumber:     QueueNumberColumn,
		IconColor:       IconColorColumn,
		IdCustomSvgIcon: IdCustomSvgIconColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
