//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SmProjectStatus = newSmProjectStatusTable("public", "sm_project_status", "")

type smProjectStatusTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnInteger
	Name            postgres.ColumnString
	Code            postgres.ColumnString
	Description     postgres.ColumnString
	UpdatedAt       postgres.ColumnTimestamp
	CreatedAt       postgres.ColumnTimestamp
	UpdatedBy       postgres.ColumnInteger
	CreatedBy       postgres.ColumnInteger
	QueueNumber     postgres.ColumnInteger
	IconColor       postgres.ColumnString
	IdCustomSvgIcon postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type SmProjectStatusTable struct {
	smProjectStatusTable

	EXCLUDED smProjectStatusTable
}

// AS creates new SmProjectStatusTable with assigned alias
func (a SmProjectStatusTable) AS(alias string) *SmProjectStatusTable {
	return newSmProjectStatusTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SmProjectStatusTable with assigned schema name
func (a SmProjectStatusTable) FromSchema(schemaName string) *SmProjectStatusTable {
	return newSmProjectStatusTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SmProjectStatusTable with assigned table prefix
func (a SmProjectStatusTable) WithPrefix(prefix string) *SmProjectStatusTable {
	return newSmProjectStatusTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SmProjectStatusTable with assigned table suffix
func (a SmProjectStatusTable) WithSuffix(suffix string) *SmProjectStatusTable {
	return newSmProjectStatusTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSmProjectStatusTable(schemaName, tableName, alias string) *SmProjectStatusTable {
	return &SmProjectStatusTable{
		smProjectStatusTable: newSmProjectStatusTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newSmProjectStatusTableImpl("", "excluded", ""),
	}
}

func newSmProjectStatusTableImpl(schemaName, tableName, alias string) smProjectStatusTable {
	var (
		IDColumn              = postgres.IntegerColumn("id")
		NameColumn            = postgres.StringColumn("name")
		CodeColumn            = postgres.StringColumn("code")
		DescriptionColumn     = postgres.StringColumn("description")
		UpdatedAtColumn       = postgres.TimestampColumn("updated_at")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		UpdatedByColumn       = postgres.IntegerColumn("updated_by")
		CreatedByColumn       = postgres.IntegerColumn("created_by")
		QueueNumberColumn     = postgres.IntegerColumn("queueNumber")
		IconColorColumn       = postgres.StringColumn("iconColor")
		IdCustomSvgIconColumn = postgres.IntegerColumn("idCustomSvgIcon")
		allColumns            = postgres.ColumnList{IDColumn, NameColumn, CodeColumn, DescriptionColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, QueueNumberColumn, IconColorColumn, IdCustomSvgIconColumn}
		mutableColumns        = postgres.ColumnList{NameColumn, CodeColumn, DescriptionColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, QueueNumberColumn, IconColorColumn, IdCustomSvgIconColumn}
	)

	return smProjectStatusTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		Name:            NameColumn,
		Code:            CodeColumn,
		Description:     DescriptionColumn,
		UpdatedAt:       UpdatedAtColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedBy:       UpdatedByColumn,
		CreatedBy:       CreatedByColumn,
		QueueNumber:     QueueNumberColumn,
		IconColor:       IconColorColumn,
		IdCustomSvgIcon: IdCustomSvgIconColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
