//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SmProjectPermissionType = newSmProjectPermissionTypeTable("public", "sm_project_permission_type", "")

type smProjectPermissionTypeTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnInteger
	Name            postgres.ColumnString
	Code            postgres.ColumnString
	Description     postgres.ColumnString
	UpdatedAt       postgres.ColumnTimestamp
	CreatedAt       postgres.ColumnTimestamp
	UpdatedBy       postgres.ColumnInteger
	CreatedBy       postgres.ColumnInteger
	QueueNumber     postgres.ColumnInteger
	IconColor       postgres.ColumnString
	IdCustomSvgIcon postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type SmProjectPermissionTypeTable struct {
	smProjectPermissionTypeTable

	EXCLUDED smProjectPermissionTypeTable
}

// AS creates new SmProjectPermissionTypeTable with assigned alias
func (a SmProjectPermissionTypeTable) AS(alias string) *SmProjectPermissionTypeTable {
	return newSmProjectPermissionTypeTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SmProjectPermissionTypeTable with assigned schema name
func (a SmProjectPermissionTypeTable) FromSchema(schemaName string) *SmProjectPermissionTypeTable {
	return newSmProjectPermissionTypeTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SmProjectPermissionTypeTable with assigned table prefix
func (a SmProjectPermissionTypeTable) WithPrefix(prefix string) *SmProjectPermissionTypeTable {
	return newSmProjectPermissionTypeTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SmProjectPermissionTypeTable with assigned table suffix
func (a SmProjectPermissionTypeTable) WithSuffix(suffix string) *SmProjectPermissionTypeTable {
	return newSmProjectPermissionTypeTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSmProjectPermissionTypeTable(schemaName, tableName, alias string) *SmProjectPermissionTypeTable {
	return &SmProjectPermissionTypeTable{
		smProjectPermissionTypeTable: newSmProjectPermissionTypeTableImpl(schemaName, tableName, alias),
		EXCLUDED:                     newSmProjectPermissionTypeTableImpl("", "excluded", ""),
	}
}

func newSmProjectPermissionTypeTableImpl(schemaName, tableName, alias string) smProjectPermissionTypeTable {
	var (
		IDColumn              = postgres.IntegerColumn("id")
		NameColumn            = postgres.StringColumn("name")
		CodeColumn            = postgres.StringColumn("code")
		DescriptionColumn     = postgres.StringColumn("description")
		UpdatedAtColumn       = postgres.TimestampColumn("updated_at")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		UpdatedByColumn       = postgres.IntegerColumn("updated_by")
		CreatedByColumn       = postgres.IntegerColumn("created_by")
		QueueNumberColumn     = postgres.IntegerColumn("queueNumber")
		IconColorColumn       = postgres.StringColumn("iconColor")
		IdCustomSvgIconColumn = postgres.IntegerColumn("idCustomSvgIcon")
		allColumns            = postgres.ColumnList{IDColumn, NameColumn, CodeColumn, DescriptionColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, QueueNumberColumn, IconColorColumn, IdCustomSvgIconColumn}
		mutableColumns        = postgres.ColumnList{NameColumn, CodeColumn, DescriptionColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, QueueNumberColumn, IconColorColumn, IdCustomSvgIconColumn}
	)

	return smProjectPermissionTypeTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		Name:            NameColumn,
		Code:            CodeColumn,
		Description:     DescriptionColumn,
		UpdatedAt:       UpdatedAtColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedBy:       UpdatedByColumn,
		CreatedBy:       CreatedByColumn,
		QueueNumber:     QueueNumberColumn,
		IconColor:       IconColorColumn,
		IdCustomSvgIcon: IdCustomSvgIconColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
