//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SmProjectTags = newSmProjectTagsTable("public", "sm_project_tags", "")

type smProjectTagsTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	ProjectID postgres.ColumnInteger
	UpdatedAt postgres.ColumnTimestamp
	CreatedAt postgres.ColumnTimestamp
	UpdatedBy postgres.ColumnInteger
	CreatedBy postgres.ColumnInteger
	TagID     postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type SmProjectTagsTable struct {
	smProjectTagsTable

	EXCLUDED smProjectTagsTable
}

// AS creates new SmProjectTagsTable with assigned alias
func (a SmProjectTagsTable) AS(alias string) *SmProjectTagsTable {
	return newSmProjectTagsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SmProjectTagsTable with assigned schema name
func (a SmProjectTagsTable) FromSchema(schemaName string) *SmProjectTagsTable {
	return newSmProjectTagsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SmProjectTagsTable with assigned table prefix
func (a SmProjectTagsTable) WithPrefix(prefix string) *SmProjectTagsTable {
	return newSmProjectTagsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SmProjectTagsTable with assigned table suffix
func (a SmProjectTagsTable) WithSuffix(suffix string) *SmProjectTagsTable {
	return newSmProjectTagsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSmProjectTagsTable(schemaName, tableName, alias string) *SmProjectTagsTable {
	return &SmProjectTagsTable{
		smProjectTagsTable: newSmProjectTagsTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newSmProjectTagsTableImpl("", "excluded", ""),
	}
}

func newSmProjectTagsTableImpl(schemaName, tableName, alias string) smProjectTagsTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		ProjectIDColumn = postgres.IntegerColumn("project_id")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedByColumn = postgres.IntegerColumn("updated_by")
		CreatedByColumn = postgres.IntegerColumn("created_by")
		TagIDColumn     = postgres.IntegerColumn("tag_id")
		allColumns      = postgres.ColumnList{IDColumn, ProjectIDColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, TagIDColumn}
		mutableColumns  = postgres.ColumnList{ProjectIDColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, TagIDColumn}
	)

	return smProjectTagsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		ProjectID: ProjectIDColumn,
		UpdatedAt: UpdatedAtColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedBy: UpdatedByColumn,
		CreatedBy: CreatedByColumn,
		TagID:     TagIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
