//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SmQuestionaryTags = newSmQuestionaryTagsTable("public", "sm_questionary_tags", "")

type smQuestionaryTagsTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	UpdatedAt postgres.ColumnTimestamp
	CreatedAt postgres.ColumnTimestamp
	UpdatedBy postgres.ColumnInteger
	CreatedBy postgres.ColumnInteger
	TagID     postgres.ColumnInteger
	SurveyID  postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type SmQuestionaryTagsTable struct {
	smQuestionaryTagsTable

	EXCLUDED smQuestionaryTagsTable
}

// AS creates new SmQuestionaryTagsTable with assigned alias
func (a SmQuestionaryTagsTable) AS(alias string) *SmQuestionaryTagsTable {
	return newSmQuestionaryTagsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SmQuestionaryTagsTable with assigned schema name
func (a SmQuestionaryTagsTable) FromSchema(schemaName string) *SmQuestionaryTagsTable {
	return newSmQuestionaryTagsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SmQuestionaryTagsTable with assigned table prefix
func (a SmQuestionaryTagsTable) WithPrefix(prefix string) *SmQuestionaryTagsTable {
	return newSmQuestionaryTagsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SmQuestionaryTagsTable with assigned table suffix
func (a SmQuestionaryTagsTable) WithSuffix(suffix string) *SmQuestionaryTagsTable {
	return newSmQuestionaryTagsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSmQuestionaryTagsTable(schemaName, tableName, alias string) *SmQuestionaryTagsTable {
	return &SmQuestionaryTagsTable{
		smQuestionaryTagsTable: newSmQuestionaryTagsTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newSmQuestionaryTagsTableImpl("", "excluded", ""),
	}
}

func newSmQuestionaryTagsTableImpl(schemaName, tableName, alias string) smQuestionaryTagsTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedByColumn = postgres.IntegerColumn("updated_by")
		CreatedByColumn = postgres.IntegerColumn("created_by")
		TagIDColumn     = postgres.IntegerColumn("tag_id")
		SurveyIDColumn  = postgres.IntegerColumn("survey_id")
		allColumns      = postgres.ColumnList{IDColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, TagIDColumn, SurveyIDColumn}
		mutableColumns  = postgres.ColumnList{UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, TagIDColumn, SurveyIDColumn}
	)

	return smQuestionaryTagsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		UpdatedAt: UpdatedAtColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedBy: UpdatedByColumn,
		CreatedBy: CreatedByColumn,
		TagID:     TagIDColumn,
		SurveyID:  SurveyIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
