//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SmTypequestionary = newSmTypequestionaryTable("public", "sm_typequestionary", "")

type smTypequestionaryTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnInteger
	Name            postgres.ColumnString
	Code            postgres.ColumnString
	Description     postgres.ColumnString
	UpdatedAt       postgres.ColumnTimestamp
	CreatedAt       postgres.ColumnTimestamp
	UpdatedBy       postgres.ColumnInteger
	CreatedBy       postgres.ColumnInteger
	QueueNumber     postgres.ColumnInteger
	IconColor       postgres.ColumnString
	IdCustomSvgIcon postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type SmTypequestionaryTable struct {
	smTypequestionaryTable

	EXCLUDED smTypequestionaryTable
}

// AS creates new SmTypequestionaryTable with assigned alias
func (a SmTypequestionaryTable) AS(alias string) *SmTypequestionaryTable {
	return newSmTypequestionaryTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SmTypequestionaryTable with assigned schema name
func (a SmTypequestionaryTable) FromSchema(schemaName string) *SmTypequestionaryTable {
	return newSmTypequestionaryTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SmTypequestionaryTable with assigned table prefix
func (a SmTypequestionaryTable) WithPrefix(prefix string) *SmTypequestionaryTable {
	return newSmTypequestionaryTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SmTypequestionaryTable with assigned table suffix
func (a SmTypequestionaryTable) WithSuffix(suffix string) *SmTypequestionaryTable {
	return newSmTypequestionaryTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSmTypequestionaryTable(schemaName, tableName, alias string) *SmTypequestionaryTable {
	return &SmTypequestionaryTable{
		smTypequestionaryTable: newSmTypequestionaryTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newSmTypequestionaryTableImpl("", "excluded", ""),
	}
}

func newSmTypequestionaryTableImpl(schemaName, tableName, alias string) smTypequestionaryTable {
	var (
		IDColumn              = postgres.IntegerColumn("id")
		NameColumn            = postgres.StringColumn("name")
		CodeColumn            = postgres.StringColumn("code")
		DescriptionColumn     = postgres.StringColumn("description")
		UpdatedAtColumn       = postgres.TimestampColumn("updated_at")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		UpdatedByColumn       = postgres.IntegerColumn("updated_by")
		CreatedByColumn       = postgres.IntegerColumn("created_by")
		QueueNumberColumn     = postgres.IntegerColumn("queueNumber")
		IconColorColumn       = postgres.StringColumn("iconColor")
		IdCustomSvgIconColumn = postgres.IntegerColumn("idCustomSvgIcon")
		allColumns            = postgres.ColumnList{IDColumn, NameColumn, CodeColumn, DescriptionColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, QueueNumberColumn, IconColorColumn, IdCustomSvgIconColumn}
		mutableColumns        = postgres.ColumnList{NameColumn, CodeColumn, DescriptionColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, QueueNumberColumn, IconColorColumn, IdCustomSvgIconColumn}
	)

	return smTypequestionaryTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		Name:            NameColumn,
		Code:            CodeColumn,
		Description:     DescriptionColumn,
		UpdatedAt:       UpdatedAtColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedBy:       UpdatedByColumn,
		CreatedBy:       CreatedByColumn,
		QueueNumber:     QueueNumberColumn,
		IconColor:       IconColorColumn,
		IdCustomSvgIcon: IdCustomSvgIconColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
