//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SubIndustries = newSubIndustriesTable("public", "sub_industries", "")

type subIndustriesTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnInteger
	Name        postgres.ColumnString
	Code        postgres.ColumnString
	Description postgres.ColumnString
	IndustryID  postgres.ColumnInteger
	CreatedAt   postgres.ColumnTimestamp
	UpdatedAt   postgres.ColumnTimestamp
	CreatedBy   postgres.ColumnInteger
	UpdatedBy   postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type SubIndustriesTable struct {
	subIndustriesTable

	EXCLUDED subIndustriesTable
}

// AS creates new SubIndustriesTable with assigned alias
func (a SubIndustriesTable) AS(alias string) *SubIndustriesTable {
	return newSubIndustriesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SubIndustriesTable with assigned schema name
func (a SubIndustriesTable) FromSchema(schemaName string) *SubIndustriesTable {
	return newSubIndustriesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SubIndustriesTable with assigned table prefix
func (a SubIndustriesTable) WithPrefix(prefix string) *SubIndustriesTable {
	return newSubIndustriesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SubIndustriesTable with assigned table suffix
func (a SubIndustriesTable) WithSuffix(suffix string) *SubIndustriesTable {
	return newSubIndustriesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSubIndustriesTable(schemaName, tableName, alias string) *SubIndustriesTable {
	return &SubIndustriesTable{
		subIndustriesTable: newSubIndustriesTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newSubIndustriesTableImpl("", "excluded", ""),
	}
}

func newSubIndustriesTableImpl(schemaName, tableName, alias string) subIndustriesTable {
	var (
		IDColumn          = postgres.IntegerColumn("id")
		NameColumn        = postgres.StringColumn("name")
		CodeColumn        = postgres.StringColumn("code")
		DescriptionColumn = postgres.StringColumn("description")
		IndustryIDColumn  = postgres.IntegerColumn("industry_id")
		CreatedAtColumn   = postgres.TimestampColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampColumn("updated_at")
		CreatedByColumn   = postgres.IntegerColumn("created_by")
		UpdatedByColumn   = postgres.IntegerColumn("updated_by")
		allColumns        = postgres.ColumnList{IDColumn, NameColumn, CodeColumn, DescriptionColumn, IndustryIDColumn, CreatedAtColumn, UpdatedAtColumn, CreatedByColumn, UpdatedByColumn}
		mutableColumns    = postgres.ColumnList{NameColumn, CodeColumn, DescriptionColumn, IndustryIDColumn, CreatedAtColumn, UpdatedAtColumn, CreatedByColumn, UpdatedByColumn}
	)

	return subIndustriesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Name:        NameColumn,
		Code:        CodeColumn,
		Description: DescriptionColumn,
		IndustryID:  IndustryIDColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,
		CreatedBy:   CreatedByColumn,
		UpdatedBy:   UpdatedByColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
