//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SurveyTags = newSurveyTagsTable("public", "survey_tags", "")

type surveyTagsTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnInteger
	Name            postgres.ColumnString
	Code            postgres.ColumnString
	Description     postgres.ColumnString
	UpdatedAt       postgres.ColumnTimestamp
	CreatedAt       postgres.ColumnTimestamp
	UpdatedBy       postgres.ColumnInteger
	CreatedBy       postgres.ColumnInteger
	QueueNumber     postgres.ColumnInteger
	IconColor       postgres.ColumnString
	IdCustomSvgIcon postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type SurveyTagsTable struct {
	surveyTagsTable

	EXCLUDED surveyTagsTable
}

// AS creates new SurveyTagsTable with assigned alias
func (a SurveyTagsTable) AS(alias string) *SurveyTagsTable {
	return newSurveyTagsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SurveyTagsTable with assigned schema name
func (a SurveyTagsTable) FromSchema(schemaName string) *SurveyTagsTable {
	return newSurveyTagsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SurveyTagsTable with assigned table prefix
func (a SurveyTagsTable) WithPrefix(prefix string) *SurveyTagsTable {
	return newSurveyTagsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SurveyTagsTable with assigned table suffix
func (a SurveyTagsTable) WithSuffix(suffix string) *SurveyTagsTable {
	return newSurveyTagsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSurveyTagsTable(schemaName, tableName, alias string) *SurveyTagsTable {
	return &SurveyTagsTable{
		surveyTagsTable: newSurveyTagsTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newSurveyTagsTableImpl("", "excluded", ""),
	}
}

func newSurveyTagsTableImpl(schemaName, tableName, alias string) surveyTagsTable {
	var (
		IDColumn              = postgres.IntegerColumn("id")
		NameColumn            = postgres.StringColumn("name")
		CodeColumn            = postgres.StringColumn("code")
		DescriptionColumn     = postgres.StringColumn("description")
		UpdatedAtColumn       = postgres.TimestampColumn("updated_at")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		UpdatedByColumn       = postgres.IntegerColumn("updated_by")
		CreatedByColumn       = postgres.IntegerColumn("created_by")
		QueueNumberColumn     = postgres.IntegerColumn("queueNumber")
		IconColorColumn       = postgres.StringColumn("iconColor")
		IdCustomSvgIconColumn = postgres.IntegerColumn("idCustomSvgIcon")
		allColumns            = postgres.ColumnList{IDColumn, NameColumn, CodeColumn, DescriptionColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, QueueNumberColumn, IconColorColumn, IdCustomSvgIconColumn}
		mutableColumns        = postgres.ColumnList{NameColumn, CodeColumn, DescriptionColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, QueueNumberColumn, IconColorColumn, IdCustomSvgIconColumn}
	)

	return surveyTagsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		Name:            NameColumn,
		Code:            CodeColumn,
		Description:     DescriptionColumn,
		UpdatedAt:       UpdatedAtColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedBy:       UpdatedByColumn,
		CreatedBy:       CreatedByColumn,
		QueueNumber:     QueueNumberColumn,
		IconColor:       IconColorColumn,
		IdCustomSvgIcon: IdCustomSvgIconColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
