//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Attributes = Attributes.FromSchema(schema)
	EmployeeOptionAttributes = EmployeeOptionAttributes.FromSchema(schema)
	Employees = Employees.FromSchema(schema)
	SmAttributeTriggers = SmAttributeTriggers.FromSchema(schema)
	SmProject = SmProject.FromSchema(schema)
	SmProjectType = SmProjectType.FromSchema(schema)
	SmSurvey = SmSurvey.FromSchema(schema)
	SmSurveyRecepients = SmSurveyRecepients.FromSchema(schema)
	SmSurveyStatus = SmSurveyStatus.FromSchema(schema)
}
