//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var TemplQuestionaryTranslate = newTemplQuestionaryTranslateTable("public", "templ_questionary_translate", "")

type templQuestionaryTranslateTable struct {
	postgres.Table

	// Columns
	ID                    postgres.ColumnInteger
	UpdatedAt             postgres.ColumnTimestamp
	CreatedAt             postgres.ColumnTimestamp
	UpdatedBy             postgres.ColumnInteger
	CreatedBy             postgres.ColumnInteger
	TemplateQuestionaryID postgres.ColumnInteger
	LanguageID            postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type TemplQuestionaryTranslateTable struct {
	templQuestionaryTranslateTable

	EXCLUDED templQuestionaryTranslateTable
}

// AS creates new TemplQuestionaryTranslateTable with assigned alias
func (a TemplQuestionaryTranslateTable) AS(alias string) *TemplQuestionaryTranslateTable {
	return newTemplQuestionaryTranslateTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TemplQuestionaryTranslateTable with assigned schema name
func (a TemplQuestionaryTranslateTable) FromSchema(schemaName string) *TemplQuestionaryTranslateTable {
	return newTemplQuestionaryTranslateTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TemplQuestionaryTranslateTable with assigned table prefix
func (a TemplQuestionaryTranslateTable) WithPrefix(prefix string) *TemplQuestionaryTranslateTable {
	return newTemplQuestionaryTranslateTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TemplQuestionaryTranslateTable with assigned table suffix
func (a TemplQuestionaryTranslateTable) WithSuffix(suffix string) *TemplQuestionaryTranslateTable {
	return newTemplQuestionaryTranslateTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTemplQuestionaryTranslateTable(schemaName, tableName, alias string) *TemplQuestionaryTranslateTable {
	return &TemplQuestionaryTranslateTable{
		templQuestionaryTranslateTable: newTemplQuestionaryTranslateTableImpl(schemaName, tableName, alias),
		EXCLUDED:                       newTemplQuestionaryTranslateTableImpl("", "excluded", ""),
	}
}

func newTemplQuestionaryTranslateTableImpl(schemaName, tableName, alias string) templQuestionaryTranslateTable {
	var (
		IDColumn                    = postgres.IntegerColumn("id")
		UpdatedAtColumn             = postgres.TimestampColumn("updated_at")
		CreatedAtColumn             = postgres.TimestampColumn("created_at")
		UpdatedByColumn             = postgres.IntegerColumn("updated_by")
		CreatedByColumn             = postgres.IntegerColumn("created_by")
		TemplateQuestionaryIDColumn = postgres.IntegerColumn("template_questionary_id")
		LanguageIDColumn            = postgres.IntegerColumn("language_id")
		allColumns                  = postgres.ColumnList{IDColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, TemplateQuestionaryIDColumn, LanguageIDColumn}
		mutableColumns              = postgres.ColumnList{UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, TemplateQuestionaryIDColumn, LanguageIDColumn}
	)

	return templQuestionaryTranslateTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                    IDColumn,
		UpdatedAt:             UpdatedAtColumn,
		CreatedAt:             CreatedAtColumn,
		UpdatedBy:             UpdatedByColumn,
		CreatedBy:             CreatedByColumn,
		TemplateQuestionaryID: TemplateQuestionaryIDColumn,
		LanguageID:            LanguageIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
