//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var TemplCommsEmail = newTemplCommsEmailTable("public", "templ_comms_email", "")

type templCommsEmailTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnInteger
	UpdatedAt       postgres.ColumnTimestamp
	CreatedAt       postgres.ColumnTimestamp
	UpdatedBy       postgres.ColumnInteger
	CreatedBy       postgres.ColumnInteger
	TemplateCommsID postgres.ColumnInteger
	LanguageID      postgres.ColumnInteger
	BodyEmail       postgres.ColumnString
	SubjectEmail    postgres.ColumnString
	CommsReminderID postgres.ColumnInteger
	IsForReport     postgres.ColumnBool

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type TemplCommsEmailTable struct {
	templCommsEmailTable

	EXCLUDED templCommsEmailTable
}

// AS creates new TemplCommsEmailTable with assigned alias
func (a TemplCommsEmailTable) AS(alias string) *TemplCommsEmailTable {
	return newTemplCommsEmailTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TemplCommsEmailTable with assigned schema name
func (a TemplCommsEmailTable) FromSchema(schemaName string) *TemplCommsEmailTable {
	return newTemplCommsEmailTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TemplCommsEmailTable with assigned table prefix
func (a TemplCommsEmailTable) WithPrefix(prefix string) *TemplCommsEmailTable {
	return newTemplCommsEmailTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TemplCommsEmailTable with assigned table suffix
func (a TemplCommsEmailTable) WithSuffix(suffix string) *TemplCommsEmailTable {
	return newTemplCommsEmailTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTemplCommsEmailTable(schemaName, tableName, alias string) *TemplCommsEmailTable {
	return &TemplCommsEmailTable{
		templCommsEmailTable: newTemplCommsEmailTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newTemplCommsEmailTableImpl("", "excluded", ""),
	}
}

func newTemplCommsEmailTableImpl(schemaName, tableName, alias string) templCommsEmailTable {
	var (
		IDColumn              = postgres.IntegerColumn("id")
		UpdatedAtColumn       = postgres.TimestampColumn("updated_at")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		UpdatedByColumn       = postgres.IntegerColumn("updated_by")
		CreatedByColumn       = postgres.IntegerColumn("created_by")
		TemplateCommsIDColumn = postgres.IntegerColumn("template_comms_id")
		LanguageIDColumn      = postgres.IntegerColumn("language_id")
		BodyEmailColumn       = postgres.StringColumn("body_email")
		SubjectEmailColumn    = postgres.StringColumn("subject_email")
		CommsReminderIDColumn = postgres.IntegerColumn("comms_reminder_id")
		IsForReportColumn     = postgres.BoolColumn("is_for_report")
		allColumns            = postgres.ColumnList{IDColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, TemplateCommsIDColumn, LanguageIDColumn, BodyEmailColumn, SubjectEmailColumn, CommsReminderIDColumn, IsForReportColumn}
		mutableColumns        = postgres.ColumnList{UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, TemplateCommsIDColumn, LanguageIDColumn, BodyEmailColumn, SubjectEmailColumn, CommsReminderIDColumn, IsForReportColumn}
	)

	return templCommsEmailTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		UpdatedAt:       UpdatedAtColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedBy:       UpdatedByColumn,
		CreatedBy:       CreatedByColumn,
		TemplateCommsID: TemplateCommsIDColumn,
		LanguageID:      LanguageIDColumn,
		BodyEmail:       BodyEmailColumn,
		SubjectEmail:    SubjectEmailColumn,
		CommsReminderID: CommsReminderIDColumn,
		IsForReport:     IsForReportColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
