//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var TemplReminderRecipientsgroup = newTemplReminderRecipientsgroupTable("public", "templ_reminder_recipientsgroup", "")

type templReminderRecipientsgroupTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnInteger
	Name            postgres.ColumnString
	Code            postgres.ColumnString
	Description     postgres.ColumnString
	UpdatedAt       postgres.ColumnTimestamp
	CreatedAt       postgres.ColumnTimestamp
	UpdatedBy       postgres.ColumnInteger
	CreatedBy       postgres.ColumnInteger
	QueueNumber     postgres.ColumnInteger
	IconColor       postgres.ColumnString
	IdCustomSvgIcon postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type TemplReminderRecipientsgroupTable struct {
	templReminderRecipientsgroupTable

	EXCLUDED templReminderRecipientsgroupTable
}

// AS creates new TemplReminderRecipientsgroupTable with assigned alias
func (a TemplReminderRecipientsgroupTable) AS(alias string) *TemplReminderRecipientsgroupTable {
	return newTemplReminderRecipientsgroupTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TemplReminderRecipientsgroupTable with assigned schema name
func (a TemplReminderRecipientsgroupTable) FromSchema(schemaName string) *TemplReminderRecipientsgroupTable {
	return newTemplReminderRecipientsgroupTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TemplReminderRecipientsgroupTable with assigned table prefix
func (a TemplReminderRecipientsgroupTable) WithPrefix(prefix string) *TemplReminderRecipientsgroupTable {
	return newTemplReminderRecipientsgroupTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TemplReminderRecipientsgroupTable with assigned table suffix
func (a TemplReminderRecipientsgroupTable) WithSuffix(suffix string) *TemplReminderRecipientsgroupTable {
	return newTemplReminderRecipientsgroupTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTemplReminderRecipientsgroupTable(schemaName, tableName, alias string) *TemplReminderRecipientsgroupTable {
	return &TemplReminderRecipientsgroupTable{
		templReminderRecipientsgroupTable: newTemplReminderRecipientsgroupTableImpl(schemaName, tableName, alias),
		EXCLUDED:                          newTemplReminderRecipientsgroupTableImpl("", "excluded", ""),
	}
}

func newTemplReminderRecipientsgroupTableImpl(schemaName, tableName, alias string) templReminderRecipientsgroupTable {
	var (
		IDColumn              = postgres.IntegerColumn("id")
		NameColumn            = postgres.StringColumn("name")
		CodeColumn            = postgres.StringColumn("code")
		DescriptionColumn     = postgres.StringColumn("description")
		UpdatedAtColumn       = postgres.TimestampColumn("updated_at")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		UpdatedByColumn       = postgres.IntegerColumn("updated_by")
		CreatedByColumn       = postgres.IntegerColumn("created_by")
		QueueNumberColumn     = postgres.IntegerColumn("queueNumber")
		IconColorColumn       = postgres.StringColumn("iconColor")
		IdCustomSvgIconColumn = postgres.IntegerColumn("idCustomSvgIcon")
		allColumns            = postgres.ColumnList{IDColumn, NameColumn, CodeColumn, DescriptionColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, QueueNumberColumn, IconColorColumn, IdCustomSvgIconColumn}
		mutableColumns        = postgres.ColumnList{NameColumn, CodeColumn, DescriptionColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, QueueNumberColumn, IconColorColumn, IdCustomSvgIconColumn}
	)

	return templReminderRecipientsgroupTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		Name:            NameColumn,
		Code:            CodeColumn,
		Description:     DescriptionColumn,
		UpdatedAt:       UpdatedAtColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedBy:       UpdatedByColumn,
		CreatedBy:       CreatedByColumn,
		QueueNumber:     QueueNumberColumn,
		IconColor:       IconColorColumn,
		IdCustomSvgIcon: IdCustomSvgIconColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
