//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var TemplCommsEntity = newTemplCommsEntityTable("public", "templ_comms_entity", "")

type templCommsEntityTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnInteger
	UpdatedAt       postgres.ColumnTimestamp
	CreatedAt       postgres.ColumnTimestamp
	UpdatedBy       postgres.ColumnInteger
	CreatedBy       postgres.ColumnInteger
	EntityID        postgres.ColumnInteger
	TemplateCommsID postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type TemplCommsEntityTable struct {
	templCommsEntityTable

	EXCLUDED templCommsEntityTable
}

// AS creates new TemplCommsEntityTable with assigned alias
func (a TemplCommsEntityTable) AS(alias string) *TemplCommsEntityTable {
	return newTemplCommsEntityTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TemplCommsEntityTable with assigned schema name
func (a TemplCommsEntityTable) FromSchema(schemaName string) *TemplCommsEntityTable {
	return newTemplCommsEntityTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TemplCommsEntityTable with assigned table prefix
func (a TemplCommsEntityTable) WithPrefix(prefix string) *TemplCommsEntityTable {
	return newTemplCommsEntityTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TemplCommsEntityTable with assigned table suffix
func (a TemplCommsEntityTable) WithSuffix(suffix string) *TemplCommsEntityTable {
	return newTemplCommsEntityTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTemplCommsEntityTable(schemaName, tableName, alias string) *TemplCommsEntityTable {
	return &TemplCommsEntityTable{
		templCommsEntityTable: newTemplCommsEntityTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newTemplCommsEntityTableImpl("", "excluded", ""),
	}
}

func newTemplCommsEntityTableImpl(schemaName, tableName, alias string) templCommsEntityTable {
	var (
		IDColumn              = postgres.IntegerColumn("id")
		UpdatedAtColumn       = postgres.TimestampColumn("updated_at")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		UpdatedByColumn       = postgres.IntegerColumn("updated_by")
		CreatedByColumn       = postgres.IntegerColumn("created_by")
		EntityIDColumn        = postgres.IntegerColumn("entity_id")
		TemplateCommsIDColumn = postgres.IntegerColumn("template_comms_id")
		allColumns            = postgres.ColumnList{IDColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, EntityIDColumn, TemplateCommsIDColumn}
		mutableColumns        = postgres.ColumnList{UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, EntityIDColumn, TemplateCommsIDColumn}
	)

	return templCommsEntityTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		UpdatedAt:       UpdatedAtColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedBy:       UpdatedByColumn,
		CreatedBy:       CreatedByColumn,
		EntityID:        EntityIDColumn,
		TemplateCommsID: TemplateCommsIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
