//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var TemplateTable = newTemplateTableTable("public", "TemplateTable", "")

type templateTableTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	UpdatedAt postgres.ColumnTimestamp
	CreatedAt postgres.ColumnTimestamp
	UpdatedBy postgres.ColumnInteger
	CreatedBy postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type TemplateTableTable struct {
	templateTableTable

	EXCLUDED templateTableTable
}

// AS creates new TemplateTableTable with assigned alias
func (a TemplateTableTable) AS(alias string) *TemplateTableTable {
	return newTemplateTableTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TemplateTableTable with assigned schema name
func (a TemplateTableTable) FromSchema(schemaName string) *TemplateTableTable {
	return newTemplateTableTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TemplateTableTable with assigned table prefix
func (a TemplateTableTable) WithPrefix(prefix string) *TemplateTableTable {
	return newTemplateTableTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TemplateTableTable with assigned table suffix
func (a TemplateTableTable) WithSuffix(suffix string) *TemplateTableTable {
	return newTemplateTableTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTemplateTableTable(schemaName, tableName, alias string) *TemplateTableTable {
	return &TemplateTableTable{
		templateTableTable: newTemplateTableTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newTemplateTableTableImpl("", "excluded", ""),
	}
}

func newTemplateTableTableImpl(schemaName, tableName, alias string) templateTableTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedByColumn = postgres.IntegerColumn("updated_by")
		CreatedByColumn = postgres.IntegerColumn("created_by")
		allColumns      = postgres.ColumnList{IDColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn}
		mutableColumns  = postgres.ColumnList{UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn}
	)

	return templateTableTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		UpdatedAt: UpdatedAtColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedBy: UpdatedByColumn,
		CreatedBy: CreatedByColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
