//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var TemplTypeAccessSurvey = newTemplTypeAccessSurveyTable("public", "templ_type_access_survey", "")

type templTypeAccessSurveyTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnInteger
	Name            postgres.ColumnString
	Code            postgres.ColumnString
	Description     postgres.ColumnString
	UpdatedAt       postgres.ColumnTimestamp
	CreatedAt       postgres.ColumnTimestamp
	UpdatedBy       postgres.ColumnInteger
	CreatedBy       postgres.ColumnInteger
	QueueNumber     postgres.ColumnInteger
	IconColor       postgres.ColumnString
	IdCustomSvgIcon postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type TemplTypeAccessSurveyTable struct {
	templTypeAccessSurveyTable

	EXCLUDED templTypeAccessSurveyTable
}

// AS creates new TemplTypeAccessSurveyTable with assigned alias
func (a TemplTypeAccessSurveyTable) AS(alias string) *TemplTypeAccessSurveyTable {
	return newTemplTypeAccessSurveyTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TemplTypeAccessSurveyTable with assigned schema name
func (a TemplTypeAccessSurveyTable) FromSchema(schemaName string) *TemplTypeAccessSurveyTable {
	return newTemplTypeAccessSurveyTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TemplTypeAccessSurveyTable with assigned table prefix
func (a TemplTypeAccessSurveyTable) WithPrefix(prefix string) *TemplTypeAccessSurveyTable {
	return newTemplTypeAccessSurveyTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TemplTypeAccessSurveyTable with assigned table suffix
func (a TemplTypeAccessSurveyTable) WithSuffix(suffix string) *TemplTypeAccessSurveyTable {
	return newTemplTypeAccessSurveyTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTemplTypeAccessSurveyTable(schemaName, tableName, alias string) *TemplTypeAccessSurveyTable {
	return &TemplTypeAccessSurveyTable{
		templTypeAccessSurveyTable: newTemplTypeAccessSurveyTableImpl(schemaName, tableName, alias),
		EXCLUDED:                   newTemplTypeAccessSurveyTableImpl("", "excluded", ""),
	}
}

func newTemplTypeAccessSurveyTableImpl(schemaName, tableName, alias string) templTypeAccessSurveyTable {
	var (
		IDColumn              = postgres.IntegerColumn("id")
		NameColumn            = postgres.StringColumn("name")
		CodeColumn            = postgres.StringColumn("code")
		DescriptionColumn     = postgres.StringColumn("description")
		UpdatedAtColumn       = postgres.TimestampColumn("updated_at")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		UpdatedByColumn       = postgres.IntegerColumn("updated_by")
		CreatedByColumn       = postgres.IntegerColumn("created_by")
		QueueNumberColumn     = postgres.IntegerColumn("queueNumber")
		IconColorColumn       = postgres.StringColumn("iconColor")
		IdCustomSvgIconColumn = postgres.IntegerColumn("idCustomSvgIcon")
		allColumns            = postgres.ColumnList{IDColumn, NameColumn, CodeColumn, DescriptionColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, QueueNumberColumn, IconColorColumn, IdCustomSvgIconColumn}
		mutableColumns        = postgres.ColumnList{NameColumn, CodeColumn, DescriptionColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, QueueNumberColumn, IconColorColumn, IdCustomSvgIconColumn}
	)

	return templTypeAccessSurveyTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		Name:            NameColumn,
		Code:            CodeColumn,
		Description:     DescriptionColumn,
		UpdatedAt:       UpdatedAtColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedBy:       UpdatedByColumn,
		CreatedBy:       CreatedByColumn,
		QueueNumber:     QueueNumberColumn,
		IconColor:       IconColorColumn,
		IdCustomSvgIcon: IdCustomSvgIconColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
