//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var TemplCommsAccess = newTemplCommsAccessTable("public", "templ_comms_access", "")

type templCommsAccessTable struct {
	postgres.Table

	// Columns
	ID               postgres.ColumnInteger
	UpdatedAt        postgres.ColumnTimestamp
	CreatedAt        postgres.ColumnTimestamp
	UpdatedBy        postgres.ColumnInteger
	CreatedBy        postgres.ColumnInteger
	TemplateCommsID  postgres.ColumnInteger
	TypeAccessSurvey postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type TemplCommsAccessTable struct {
	templCommsAccessTable

	EXCLUDED templCommsAccessTable
}

// AS creates new TemplCommsAccessTable with assigned alias
func (a TemplCommsAccessTable) AS(alias string) *TemplCommsAccessTable {
	return newTemplCommsAccessTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TemplCommsAccessTable with assigned schema name
func (a TemplCommsAccessTable) FromSchema(schemaName string) *TemplCommsAccessTable {
	return newTemplCommsAccessTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TemplCommsAccessTable with assigned table prefix
func (a TemplCommsAccessTable) WithPrefix(prefix string) *TemplCommsAccessTable {
	return newTemplCommsAccessTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TemplCommsAccessTable with assigned table suffix
func (a TemplCommsAccessTable) WithSuffix(suffix string) *TemplCommsAccessTable {
	return newTemplCommsAccessTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTemplCommsAccessTable(schemaName, tableName, alias string) *TemplCommsAccessTable {
	return &TemplCommsAccessTable{
		templCommsAccessTable: newTemplCommsAccessTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newTemplCommsAccessTableImpl("", "excluded", ""),
	}
}

func newTemplCommsAccessTableImpl(schemaName, tableName, alias string) templCommsAccessTable {
	var (
		IDColumn               = postgres.IntegerColumn("id")
		UpdatedAtColumn        = postgres.TimestampColumn("updated_at")
		CreatedAtColumn        = postgres.TimestampColumn("created_at")
		UpdatedByColumn        = postgres.IntegerColumn("updated_by")
		CreatedByColumn        = postgres.IntegerColumn("created_by")
		TemplateCommsIDColumn  = postgres.IntegerColumn("template_comms_id")
		TypeAccessSurveyColumn = postgres.IntegerColumn("type_access_survey")
		allColumns             = postgres.ColumnList{IDColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, TemplateCommsIDColumn, TypeAccessSurveyColumn}
		mutableColumns         = postgres.ColumnList{UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, TemplateCommsIDColumn, TypeAccessSurveyColumn}
	)

	return templCommsAccessTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:               IDColumn,
		UpdatedAt:        UpdatedAtColumn,
		CreatedAt:        CreatedAtColumn,
		UpdatedBy:        UpdatedByColumn,
		CreatedBy:        CreatedByColumn,
		TemplateCommsID:  TemplateCommsIDColumn,
		TypeAccessSurvey: TypeAccessSurveyColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
