//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var TemplRecomendedFrequancy = newTemplRecomendedFrequancyTable("public", "templ_recomended_frequancy", "")

type templRecomendedFrequancyTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnInteger
	Name            postgres.ColumnString
	Code            postgres.ColumnString
	Description     postgres.ColumnString
	UpdatedAt       postgres.ColumnTimestamp
	CreatedAt       postgres.ColumnTimestamp
	UpdatedBy       postgres.ColumnInteger
	CreatedBy       postgres.ColumnInteger
	QueueNumber     postgres.ColumnInteger
	IconColor       postgres.ColumnString
	IdCustomSvgIcon postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type TemplRecomendedFrequancyTable struct {
	templRecomendedFrequancyTable

	EXCLUDED templRecomendedFrequancyTable
}

// AS creates new TemplRecomendedFrequancyTable with assigned alias
func (a TemplRecomendedFrequancyTable) AS(alias string) *TemplRecomendedFrequancyTable {
	return newTemplRecomendedFrequancyTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TemplRecomendedFrequancyTable with assigned schema name
func (a TemplRecomendedFrequancyTable) FromSchema(schemaName string) *TemplRecomendedFrequancyTable {
	return newTemplRecomendedFrequancyTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TemplRecomendedFrequancyTable with assigned table prefix
func (a TemplRecomendedFrequancyTable) WithPrefix(prefix string) *TemplRecomendedFrequancyTable {
	return newTemplRecomendedFrequancyTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TemplRecomendedFrequancyTable with assigned table suffix
func (a TemplRecomendedFrequancyTable) WithSuffix(suffix string) *TemplRecomendedFrequancyTable {
	return newTemplRecomendedFrequancyTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTemplRecomendedFrequancyTable(schemaName, tableName, alias string) *TemplRecomendedFrequancyTable {
	return &TemplRecomendedFrequancyTable{
		templRecomendedFrequancyTable: newTemplRecomendedFrequancyTableImpl(schemaName, tableName, alias),
		EXCLUDED:                      newTemplRecomendedFrequancyTableImpl("", "excluded", ""),
	}
}

func newTemplRecomendedFrequancyTableImpl(schemaName, tableName, alias string) templRecomendedFrequancyTable {
	var (
		IDColumn              = postgres.IntegerColumn("id")
		NameColumn            = postgres.StringColumn("name")
		CodeColumn            = postgres.StringColumn("code")
		DescriptionColumn     = postgres.StringColumn("description")
		UpdatedAtColumn       = postgres.TimestampColumn("updated_at")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		UpdatedByColumn       = postgres.IntegerColumn("updated_by")
		CreatedByColumn       = postgres.IntegerColumn("created_by")
		QueueNumberColumn     = postgres.IntegerColumn("queueNumber")
		IconColorColumn       = postgres.StringColumn("iconColor")
		IdCustomSvgIconColumn = postgres.IntegerColumn("idCustomSvgIcon")
		allColumns            = postgres.ColumnList{IDColumn, NameColumn, CodeColumn, DescriptionColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, QueueNumberColumn, IconColorColumn, IdCustomSvgIconColumn}
		mutableColumns        = postgres.ColumnList{NameColumn, CodeColumn, DescriptionColumn, UpdatedAtColumn, CreatedAtColumn, UpdatedByColumn, CreatedByColumn, QueueNumberColumn, IconColorColumn, IdCustomSvgIconColumn}
	)

	return templRecomendedFrequancyTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		Name:            NameColumn,
		Code:            CodeColumn,
		Description:     DescriptionColumn,
		UpdatedAt:       UpdatedAtColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedBy:       UpdatedByColumn,
		CreatedBy:       CreatedByColumn,
		QueueNumber:     QueueNumberColumn,
		IconColor:       IconColorColumn,
		IdCustomSvgIcon: IdCustomSvgIconColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
