//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type AccountRoleStatuses struct {
	ID                 int32 `sql:"primary_key"`
	CreatedAt          *time.Time
	UpdatedAt          *time.Time
	CreatedBy          *int32
	UpdatedBy          *int32
	DateSentInvitation *time.Time
	DateAccept         *time.Time
	Active             *bool
	DateExpired        *time.Time
	InviteStatusID     int32
	UserID             int32
	RoleID             int32
}
