//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Employees struct {
	ID              int32 `sql:"primary_key"`
	PrefferedName   *string
	FullName        *string
	Identity        *string
	FristSeen       *time.Time
	HubspotObjectID *string
	HrisRemoteID    *string
	UpdatedAt       *time.Time
	CreatedAt       *time.Time
	UpdatedBy       *int32
	CreatedBy       *int32
	Email           *string
}
