//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type EmployeeImport struct {
	ID                    int32 `sql:"primary_key"`
	ImportedAt            *time.Time
	CreatedAt             *time.Time
	UpdatedAt             *time.Time
	RemoveAbsentEmployees *bool
	EntityID              *int32
	ImportTypeID          *int32
	CreatedBy             *int32
	UpdatedBy             *int32
	ChangesImport         *string
	ErrorsImport          *string
}
