//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type EntitySettings struct {
	ID              int32 `sql:"primary_key"`
	Name            *string
	AdminCount      *int32
	UserCount       *int32
	EmployeeCount   *int32
	ActiveSeatCount *int32
	BeginDate       *time.Time
	EndDate         *time.Time
	EntityID        int32
}
