//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Entity struct {
	ID                           int32 `sql:"primary_key"`
	Name                         *string
	WorkspaceID                  int32
	CompanyStatusID              *int32
	CustomerStatusID             *int32
	OrganizationSizeCategoriesID *int32
	BoldBiSiteName               *string
	Details                      *string
	ImportLock                   *bool
	CreatedBy                    *int32
	UpdatedBy                    *int32
	CreatedAt                    *time.Time
	UpdatedAt                    *time.Time
	LogoID                       *int32
	IDOrgstructure               *int32
}
