//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type EntityAttributes struct {
	ID              int32 `sql:"primary_key"`
	Name            *string
	Type            *string
	EntityID        *int32
	CreatedAt       *time.Time
	UpdatedAt       *time.Time
	CreatedBy       *int32
	UpdatedBy       *int32
	IDParentattr    *int32
	IDAttributetype *int32
}
