//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type EntitiesSubIndustries struct {
	ID              int32 `sql:"primary_key"`
	EntitiesID      *int32
	SubIndustriesID *int32
}
