//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type RolePermission struct {
	ID                int32 `sql:"primary_key"`
	RoleID            int32
	LevelPermissionID int32
}
