//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SmIsInvitesend struct {
	ID                int32 `sql:"primary_key"`
	UpdatedAt         *time.Time
	CreatedBy         *int32
	CreatedAt         *time.Time
	UpdatedBy         *int32
	SurveyRecipientID int32
	DateTimeSend      *time.Time
	IsInvite          *bool
	EmailtemplateID   int32
	IsReminder        *bool
}
