//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SmProjectPermissions struct {
	ID        int32 `sql:"primary_key"`
	ProjectID int32
	RoleID    int32
	UpdatedAt *time.Time
	CreatedBy *int32
	CreatedAt *time.Time
	UpdatedBy *int32
	TypeID    int32
}
