//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SmProject struct {
	ID                       int32 `sql:"primary_key"`
	Name                     *string
	ProjecttypeID            int32
	MinResponses             *int32
	DateEnd                  *time.Time
	AccessLink               *string
	UpdatedAt                *time.Time
	CreatedAt                *time.Time
	UpdatedBy                *int32
	CreatedBy                *int32
	DateAttributeMilestoneID *int32
}
