//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SmSurveyRecepients struct {
	ID                int32 `sql:"primary_key"`
	SurveyID          int32
	EmployeeID        *int32
	Automatical       *bool
	AccessCode        *string
	UpdatedAt         *time.Time
	CreatedBy         *int32
	CreatedAt         *time.Time
	UpdatedBy         *int32
	MilestoneDateSend *time.Time
	Answered          *bool
	Answers           *string
}
