//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SmSurveyRating struct {
	ID          int32 `sql:"primary_key"`
	SurveyID    int32
	Name        *string
	OrderNumber *int32
	UpdatedAt   *time.Time
	CreatedBy   *int32
	CreatedAt   *time.Time
	UpdatedBy   *int32
	Score       *int32
}
