//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SmSurvey struct {
	ID                    int32 `sql:"primary_key"`
	Name                  *string
	UpdatedAt             *time.Time
	CreatedAt             *time.Time
	UpdatedBy             *int32
	CreatedBy             *int32
	FinishMessage         *string
	StatusID              int32
	ProjectID             int32
	MilestoneDay          *int32
	StartDateAttributeID  *int32
	CommsHeaderLogo       *string
	CommsIsSendReport     *bool
	CommsTimeSendReport   *time.Time
	SurveyDateStart       *time.Time
	SurveyDateEnd         *time.Time
	CommsReminderDaysID   *int32
	Number                *string
	QuestionaryEstimation *string
	QuestionarySurvey     *string
	QuestionaryTypeID     *int32
	TimestartMilestone    *time.Time
	LaunchedLastDate      *time.Time
	DatatimeNextstart     *time.Time
	LeaveDateEmpty        *bool
}
