//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Workspace struct {
	ID             int32 `sql:"primary_key"`
	Name           *string
	ProjM          *bool
	Industry       *string
	SignInMethod   *int32
	Demo           *bool
	UpdatedAt      *time.Time
	UpdatedBy      *int32
	CreatedBy      *int32
	CreatedAt      *time.Time
	CompanyLogoID  *int32
	CompanyLogoURL *string
}
