name: tests
on:
  pull_request:


env:
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432
  POSTGRES_USER: template-api
  POSTGRES_PASSWORD: template-api
  POSTGRES_DB: template-api
  NATS_HOST: localhost
  NATS_PORT: 4222
  GOOSE_DRIVER: postgres
  GOOSE_DBSTRING: host=localhost user=template-api password=template-api dbname=template-api sslmode=disable

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name postgres-service
        ports:
          - 5432:5432
      nats:
        image: nats:2.10
        ports:
          - 8222:8222
          - 4222:4222
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set private repo
        run: git config --global url."https://${{ secrets.GH_PRIVATE_TOKEN }}@github.com".insteadOf "https://github.com"

      - name: set up Go
        uses: actions/setup-go@v4
        with:
          cache: true
          go-version-file: go.mod

      - name: install goose
        run: "go install github.com/pressly/goose/v3/cmd/goose@v3.17.0"

      - name: apply migrations
        run: make -e DB_MIGRATIONS_URL=https://github.com/engagerocketco/db-migrations.git migrate

      - name: test-report
        run: make test
